Sign In and Sign Up implemented
basliqacademy/FarazPourebrahim pull request #4
Opened 2024-08-19 10:26 UTC by FarazPourebrahim

2024-08-21 08:13 UTC, atareversei requested changes

2024-08-21 08:13 UTC, atareversei commented on SET_internship/public/SignUpCard.png
use webp instead

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/App.css
import standalone css files in this global css file to manage styles

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/App.tsx
> +        </Router>
extract theses routes into their own files
https://reactrouter.com/en/main/routers/create-browser-router

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/api/connect.ts
> +}
discriminated union

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/api/connect.ts
> +                }
redundant try/catch block

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/api/endpoints.ts
> +const BASE_URL: string = "http://45.159.149.130:99";
add api version as a variable
add api endpoints

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/api/connect.ts
> +            const result: ApiResponse = {
check res.status

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/api/connect.ts
> +
add static field for token

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/components/dashboard/Dashboard.tsx
> +                const data = await connect.get('api/v1/authenticated/me',{headers: {
refactor authorization header

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/components/signin/SignInForm.module.css
> +html, body {
```css
*, *::before, *::after {
 margin: 0;
 padding: 0;
 box-sizing: border-box;
}
```

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/components/signin/SignInForm.module.css
> +    height: 100%;
```css
body {
 min-height: 100dvh;
}
```

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/components/signin/SignInForm.tsx
> +            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
take these into a common utility file or class

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/components/signin/SignInForm.tsx
> +            let requestBody = {};
create and api layer with strongly typed inputs and outputs

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/components/signin/SignInForm.tsx
> +                            <a onClick={() => navigate("/sign_up")} className={styles["link-spacing"]}>{PERSIAN.enter_with_otp}</a>
https://reactrouter.com/en/main/components/link

2024-08-21 08:13 UTC, atareversei commented on SET_internship/src/utils/toast/toastStyles.css
> +*{
:root

2024-08-25 14:28 UTC, atareversei requested changes

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/api/connect.ts
>      NETWORK = 'network',
unified enum types

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/api/connect.ts
> +    errorType: ApiErrorType;
form errors

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/api/connect.ts
> +                return {
check status

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/api/connect.ts
>      }
add patch method

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/api/connect.ts
> +                return { success: true, data };
data: data.data as T

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/api/api.ts
> +    },
remove generic type from function signature 
and define request and response types and add them to the function
and don't forget to pass the response type to generic argument slot

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/api/api.ts
> +                'Authorization': `Bearer ${Connect.token}`,
move token assignment into connect class

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/api/endpoints.ts
> +}
getter function

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/components/components/Anchor/Anchor.tsx
> +        <Link className={`${s[color]} ${s[hover]} ${s[underline]}`} {...rest}>
does this component handle navigating to absolute URLs like `https://google.com`?

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/components/components/Anchor/Anchor.tsx
> +type Hover = 'none' | 'underline' | 'blue-underline';
extra type

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/context/UserContext.tsx
> +    const [user, setUser] = useState<any>(null);
add use effect

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/components/signin/SignInForm.module.css
> +    min-height: 100vh;
dvh

2024-08-25 14:28 UTC, atareversei commented on SET_internship/src/components/signin/SignInForm.tsx
> +        Connect.configure(BASE_URL);
add config before app has been initialized

2024-08-27 07:29 UTC, FarazPourebrahim commented on SET_internship/src/components/components/Anchor/Anchor.tsx
> +        <Link className={`${s[color]} ${s[hover]} ${s[underline]}`} {...rest}>
Yes it does

2024-08-27 09:32 UTC, FarazPourebrahim commented on SET_internship/src/api/api.ts
> +    },
I have a problem with this

2024-09-22 12:37 UTC, atareversei requested changes

2024-09-22 12:37 UTC, atareversei commented on SET_internship/src/api/api.ts
move this file into a new directory call `/services` and rename this file to `auth.ts`

2024-09-22 12:37 UTC, atareversei commented on SET_internship/src/api/connect.ts
> +    formError?: {};
`Record<string, string[]>` or `{ [key: string]: string[] }`

2024-09-22 12:37 UTC, atareversei commented on SET_internship/src/components/signup/SignUpForm.tsx
> +                        localStorage.setItem('authentication-token', json.data.token);
convert to a function on context

2024-09-22 12:37 UTC, atareversei commented on SET_internship/src/components/signup/SignUpForm.tsx
> +                            <Anchor color={'black'} underline={"on-hover"} onClick={() => setPhase(Phases.PHONE_NUMBER)} to={'/sign_up'}>
redundant setPhase

2024-12-21 17:59 UTC, merged